@startuml
'https://plantuml.com/sequence-diagram

autonumber
FrondEnd -> RuleService++: DELETE api /rule-management/v1/data-models/{data-model-id}/attribute/{attribute-id}
RuleService --> RuleService++: Validate path variable
RuleService --> RuleService--: End validate
RuleService -> RuleDB++: get attribute exist
RuleService <-- RuleDB--: Return result
RuleService -> RuleDB++: update attribute status to DELETE
RuleService <-- RuleDB--: Return result
FrondEnd <-- RuleService--: Return response
@enduml